"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-28 23:31:36.213302
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benchmark_apps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('prelaunch_info', sa.Text(), nullable=False),
    sa.Column('group', sa.String(length=10), nullable=False),
    sa.CheckConstraint('"group" IN (\'calib\', \'eval\')', name=op.f('ck_benchmark_apps_group')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_benchmark_apps'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('benchmark_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('labeler_id', sa.String(length=20), nullable=False),
    sa.CheckConstraint('"category" IN (\'UNCLEAR_PURPOSE\', \'TOO_MANY_STEPS\', \'PRIVACY\', \'PRICE\', \'TRUST\', \'FEATURE_MISSING\', \'SWITCHING_COST\', \'NAVIGATION_LOST\', \'OTHER\')', name=op.f('ck_benchmark_issues_category')),
    sa.ForeignKeyConstraint(['app_id'], ['benchmark_apps.id'], name=op.f('fk_benchmark_issues_app_id_benchmark_apps'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_benchmark_issues'))
    )
    op.create_index(op.f('ix_benchmark_issues_app_id'), 'benchmark_issues', ['app_id'], unique=False)
    op.create_table('studies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_studies_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_studies'))
    )
    op.create_index(op.f('ix_studies_user_id'), 'studies', ['user_id'], unique=False)
    op.create_table('calibrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('metric', sa.String(length=50), nullable=False),
    sa.Column('ai_value', sa.Float(), nullable=False),
    sa.Column('real_value', sa.Float(), nullable=False),
    sa.Column('gap', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], name=op.f('fk_calibrations_study_id_studies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calibrations'))
    )
    op.create_index(op.f('ix_calibrations_study_id'), 'calibrations', ['study_id'], unique=False)
    op.create_table('invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], name=op.f('fk_invites_study_id_studies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invites')),
    sa.UniqueConstraint('token', name=op.f('uq_invites_token'))
    )
    op.create_index(op.f('ix_invites_study_id'), 'invites', ['study_id'], unique=False)
    op.create_table('personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('attributes_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], name=op.f('fk_personas_study_id_studies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_personas'))
    )
    op.create_index(op.f('ix_personas_study_id'), 'personas', ['study_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('features_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('price', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], name=op.f('fk_products_study_id_studies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_index(op.f('ix_products_study_id'), 'products', ['study_id'], unique=False)
    op.create_table('prototypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('figma_url', sa.Text(), nullable=True),
    sa.Column('screens_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('links_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], name=op.f('fk_prototypes_study_id_studies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prototypes'))
    )
    op.create_index(op.f('ix_prototypes_study_id'), 'prototypes', ['study_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], name=op.f('fk_questions_study_id_studies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions'))
    )
    op.create_index(op.f('ix_questions_study_id'), 'questions', ['study_id'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('progress', sa.Float(), server_default='0', nullable=False),
    sa.CheckConstraint('"mode" IN (\'ask\', \'act\')', name=op.f('ck_runs_mode')),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], name=op.f('fk_runs_study_id_studies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runs'))
    )
    op.create_index(op.f('ix_runs_study_id'), 'runs', ['study_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('goal_screen_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], name=op.f('fk_tasks_study_id_studies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index(op.f('ix_tasks_study_id'), 'tasks', ['study_id'], unique=False)
    op.create_table('act_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('participant_type', sa.String(length=10), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('turn', sa.Integer(), nullable=False),
    sa.Column('screen_id', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('target', sa.Text(), nullable=True),
    sa.Column('drop_reason', sa.String(length=30), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.CheckConstraint('"drop_reason" IN (\'UNCLEAR_PURPOSE\', \'TOO_MANY_STEPS\', \'PRIVACY\', \'PRICE\', \'TRUST\', \'FEATURE_MISSING\', \'SWITCHING_COST\', \'NAVIGATION_LOST\', \'MAX_TURNS\')', name=op.f('ck_act_logs_drop_reason')),
    sa.CheckConstraint('"participant_type" IN (\'ai\', \'real\')', name=op.f('ck_act_logs_participant_type')),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_act_logs_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_act_logs'))
    )
    op.create_index(op.f('ix_act_logs_run_id'), 'act_logs', ['run_id'], unique=False)
    op.create_table('ask_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('response_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], name=op.f('fk_ask_responses_persona_id_personas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_ask_responses_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ask_responses'))
    )
    op.create_index(op.f('ix_ask_responses_persona_id'), 'ask_responses', ['persona_id'], unique=False)
    op.create_index(op.f('ix_ask_responses_run_id'), 'ask_responses', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ask_responses_run_id'), table_name='ask_responses')
    op.drop_index(op.f('ix_ask_responses_persona_id'), table_name='ask_responses')
    op.drop_table('ask_responses')
    op.drop_index(op.f('ix_act_logs_run_id'), table_name='act_logs')
    op.drop_table('act_logs')
    op.drop_index(op.f('ix_tasks_study_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_runs_study_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_questions_study_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_prototypes_study_id'), table_name='prototypes')
    op.drop_table('prototypes')
    op.drop_index(op.f('ix_products_study_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_personas_study_id'), table_name='personas')
    op.drop_table('personas')
    op.drop_index(op.f('ix_invites_study_id'), table_name='invites')
    op.drop_table('invites')
    op.drop_index(op.f('ix_calibrations_study_id'), table_name='calibrations')
    op.drop_table('calibrations')
    op.drop_index(op.f('ix_studies_user_id'), table_name='studies')
    op.drop_table('studies')
    op.drop_index(op.f('ix_benchmark_issues_app_id'), table_name='benchmark_issues')
    op.drop_table('benchmark_issues')
    op.drop_table('users')
    op.drop_table('benchmark_apps')
    # ### end Alembic commands ###
